### ISSUE TITLE
TypeError: Object of type DataFrame is not serializable

### ISSUE THREAD

**Issue by jimthompson5802** [jimthompson5802/connection_solver#46]
When using checkpointer (`MemorySaver()`) encountering error at completion of workflow

Running Connection Solver Agent with EmbedVec Recommender 0.7.1-dev

ENTERED SETUP_PUZZLE
Enter 'file' to read words from a file or 'image' to read words from an image: file
Please enter the word file location: data/word_list5.txt
Puzzle Words: ['uphold', 'discard', 'honor', 'energy', 'state', 'play', 'justice', 'labor', 'pass', 'fulfill', 'draw', 'keep', 'blanket', 'sham', 'sheet', 'throw']

Generating vocabulary for the words...this may take about a minute

Generating embeddings for the definitions

ENTERED EMBEDVEC_RECOMMENDER
found count: 0, mistake_count: 0
(123, 123)
(123, 123)
candidate_lists size: 85

EMBEDVEC_RECOMMENDER: RECOMMENDED WORDS ['blanket', 'sham', 'sheet', 'throw'] with connection This group is connected by the theme of bedding or coverings, unlike the others which are related to fulfilling obligations.
Is the recommendation accepted? (y/g/b/p/m/o/n): g
Recommendation ['blanket', 'sham', 'sheet', 'throw'] is correct

ENTERED EMBEDVEC_RECOMMENDER
found count: 1, mistake_count: 0
(92, 92)
(92, 92)
candidate_lists size: 59

EMBEDVEC_RECOMMENDER: RECOMMENDED WORDS ['fulfill', 'honor', 'keep', 'uphold'] with connection The words in this group are connected by the theme of completing or maintaining an obligation or duty.
Is the recommendation accepted? (y/g/b/p/m/o/n): y
Recommendation ['fulfill', 'honor', 'keep', 'uphold'] is correct

ENTERED EMBEDVEC_RECOMMENDER
found count: 2, mistake_count: 0
(68, 68)
(68, 68)
candidate_lists size: 23

EMBEDVEC_RECOMMENDER: RECOMMENDED WORDS ['discard', 'draw', 'pass', 'play'] with connection This group is connected by the theme of actions related to games or card games.
Is the recommendation accepted? (y/g/b/p/m/o/n): b
Recommendation ['discard', 'draw', 'pass', 'play'] is correct

ENTERED EMBEDVEC_RECOMMENDER
found count: 3, mistake_count: 0
(28, 28)
(28, 28)
candidate_lists size: 1

EMBEDVEC_RECOMMENDER: RECOMMENDED WORDS ['energy', 'justice', 'labor', 'state'] with connection The words are not connected by a single theme or concept. Each term represents distinct concepts: energy (power or capacity), justice (law or fairness), labor (work), and state (condition or government).
Is the recommendation accepted? (y/g/b/p/m/o/n): p
Recommendation ['energy', 'justice', 'labor', 'state'] is correct
SOLVED THE CONNECTION PUZZLE!!!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 471, in <module>
    result = run_workflow(workflow_graph, initial_state, runtime_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 372, in run_workflow
    result = workflow_graph.invoke(initial_state, runtime_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1927, in invoke
    for chunk in self.stream(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1596, in stream
    with SyncPregelLoop(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 874, in __exit__
    return self.stack.__exit__(exc_type, exc_value, traceback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 601, in __exit__
    raise exc_details[1]
  File "/usr/local/lib/python3.11/contextlib.py", line 586, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/executor.py", line 107, in __exit__
    task.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/executor.py", line 70, in done
    task.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/memory/__init__.py", line 384, in put_writes
    self.writes[outer_key][inner_key] = (task_id, c, self.serde.dumps_typed(v))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 193, in dumps_typed
    return "msgpack", _msgpack_enc(obj)
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 502, in _msgpack_enc
    return enc.pack(data)
           ^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 276, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 267, in msgpack._cmsgpack.Packer._pack
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 435, in _msgpack_default
    raise TypeError(f"Object of type {obj.__class__.__name__} is not serializable")
TypeError: Object of type DataFrame is not serializable

**Comment by jimthompson5802** [comment]
After converting the `state["vocabulary_df"]` to a dictionary, encountering this problem

Running Connection Solver Agent with EmbedVec Recommender 0.7.1-dev

ENTERED SETUP_PUZZLE
Enter 'file' to read words from a file or 'image' to read words from an image: file
Please enter the word file location: data/word_list5.txt
Puzzle Words: ['uphold', 'discard', 'honor', 'energy', 'state', 'play', 'justice', 'labor', 'pass', 'fulfill', 'draw', 'keep', 'blanket', 'sham', 'sheet', 'throw']

Generating vocabulary for the words...this may take about a minute

Generating embeddings for the definitions

ENTERED EMBEDVEC_RECOMMENDER
found count: 0, mistake_count: 0
(124, 124)
(124, 124)
candidate_lists size: 76

EMBEDVEC_RECOMMENDER: RECOMMENDED WORDS ['blanket', 'sham', 'sheet', 'throw'] with connection All words are related to coverings or types of fabric used for bedding.
Is the recommendation accepted? (y/g/b/p/m/o/n): g
Recommendation ['blanket', 'sham', 'sheet', 'throw'] is correct

ENTERED EMBEDVEC_RECOMMENDER
found count: 1, mistake_count: 0
(96, 96)
(96, 96)
candidate_lists size: 53

EMBEDVEC_RECOMMENDER: RECOMMENDED WORDS ['honor', 'justice', 'keep', 'uphold'] with connection This group is unified by the theme of maintaining moral integrity and standards, focusing on principles of honor and justice.
Is the recommendation accepted? (y/g/b/p/m/o/n): n
Recommendation ['honor', 'justice', 'keep', 'uphold'] is incorrect
Changing the recommender from 'embedvec_recommender' to 'llm_recommender'

ENTERED LLM_RECOMMENDER
found count: 1, mistake_count: 1
attempt_count: 1
words_remaining: ['discard', 'draw', 'state', 'uphold', 'labor', 'justice', 'honor', 'fulfill', 'keep', 'pass', 'energy', 'play']

LLM_RECOMMENDER: RECOMMENDED WORDS ['energy', 'justice', 'labor', 'state'] with connection Departments of the U.S. government
Is the recommendation accepted? (y/g/b/p/m/o/n): p
Recommendation ['energy', 'justice', 'labor', 'state'] is correct

ENTERED LLM_RECOMMENDER
found count: 2, mistake_count: 1
attempt_count: 1
words_remaining: ['honor', 'uphold', 'play', 'draw', 'keep', 'pass', 'fulfill', 'discard']

LLM_RECOMMENDER: RECOMMENDED WORDS ['fulfill', 'honor', 'keep', 'uphold'] with connection Actions related to maintaining or adhering to something (such as a promise or duty)
Is the recommendation accepted? (y/g/b/p/m/o/n): y
Recommendation ['fulfill', 'honor', 'keep', 'uphold'] is correct

ENTERED LLM_RECOMMENDER
found count: 3, mistake_count: 1
attempt_count: 1
words_remaining: ['discard', 'pass', 'draw', 'play']

LLM_RECOMMENDER: RECOMMENDED WORDS ['discard', 'draw', 'pass', 'play'] with connection actions in card games
Is the recommendation accepted? (y/g/b/p/m/o/n): b
Recommendation ['discard', 'draw', 'pass', 'play'] is correct
SOLVED THE CONNECTION PUZZLE!!!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/vscode/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 472, in <module>
    result = run_workflow(workflow_graph, initial_state, runtime_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 373, in run_workflow
    result = workflow_graph.invoke(initial_state, runtime_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1927, in invoke
    for chunk in self.stream(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1596, in stream
    with SyncPregelLoop(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/loop.py", line 874, in __exit__
    return self.stack.__exit__(exc_type, exc_value, traceback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 601, in __exit__
    raise exc_details[1]
  File "/usr/local/lib/python3.11/contextlib.py", line 586, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/executor.py", line 107, in __exit__
    task.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/executor.py", line 70, in done
    task.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/memory/__init__.py", line 384, in put_writes
    self.writes[outer_key][inner_key] = (task_id, c, self.serde.dumps_typed(v))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 193, in dumps_typed
    return "msgpack", _msgpack_enc(obj)
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 502, in _msgpack_enc
    return enc.pack(data)
           ^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 279, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 276, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 265, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 213, in msgpack._cmsgpack.Packer._pack_inner
  File "msgpack/_packer.pyx", line 267, in msgpack._cmsgpack.Packer._pack
  File "/usr/local/lib/python3.11/site-packages/langgraph/checkpoint/serde/jsonplus.py", line 435, in _msgpack_default
    raise TypeError(f"Object of type {obj.__class__.__name__} is not serializable")
TypeError: Object of type ndarray is not serializable

**Comment by jimthompson5802** [comment]
Moved vocabulary from state dictionary to sqlite database.  Addressed in PR #47
