### ISSUE TITLE
KeyError when puzzle word is a "ti (musical note)"

### ISSUE THREAD

**Issue by jimthompson5802** [jimthompson5802/connection_solver#63]
Error occurred for 2024_12_12 puzzle.

**Log**

```text
vscode ➜ /workspaces/connection_solver (main) $ python src/agent/app_embedvec.py 
Running Connection Solver Agent with EmbedVec Recommender 0.9.1
Enter 'file' to read words from a file or 'image' to read words from an image: image
Please enter the file/image location: /desktop/connection_puzzle_2024_12_12.png
Setting up Puzzle Words: ['fudge', 'bed', 'saw', 'tee (shirt)', 'ti (musical note)', 'gear', 'rats', 'delta', 'zipper', 'nuts', 'tea', 'geez', 'mouth', 'tee (golf)', 'comb', 'bank']

ENTERED SETUP_PUZZLE

Generating vocabulary and embeddings for the words...this may take several seconds 
Traceback (most recent call last):
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 150, in <module>
    asyncio.run(main(manual_puzzle_setup_prompt, interact_with_user))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 137, in main
    result = await run_workflow(
             ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 912, in run_workflow
    async for chunk in workflow_graph.astream(None, runtime_config, stream_mode="values"):
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/__init__.py", line 1867, in astream
    async for _ in runner.atick(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/runner.py", line 222, in atick
    await arun_with_retry(
  File "/usr/local/lib/python3.11/site-packages/langgraph/pregel/retry.py", line 138, in arun_with_retry
    await task.proc.ainvoke(task.input, config)
  File "/usr/local/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 453, in ainvoke
    input = await asyncio.create_task(coro, context=context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langgraph/utils/runnable.py", line 236, in ainvoke
    ret = await asyncio.create_task(coro, context=context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 145, in setup_puzzle
    vocabulary = await generate_vocabulary(state["words_remaining"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 232, in generate_vocabulary
    await asyncio.gather(*[process_word(word) for word in words])
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 230, in process_word
    vocabulary[the_word] = json.loads(result.content)[the_word]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'ti (musical note)'
During task with name 'setup_puzzle' and id 'd73384ae-5429-7fa2-4a4f-c5d51a35da70'
vscode ➜ /workspaces/connection_solver (main) $ 
```

Puzzle image
<img width="607" alt="image" src="https://github.com/user-attachments/assets/9678ca6c-45fd-4f12-9fd1-7c203a67a1b5" />

**Comment by jimthompson5802** [comment]
In debugger failure here
```python
    async def process_word(the_word):
        prompt = f"\n\ngiven word: {the_word}"
        prompt = HumanMessage(prompt)
        prompt = [SYSTEM_MESSAGE, prompt]
        result = await llm.ainvoke(prompt)
        vocabulary[the_word] = json.loads(result.content)[the_word]
```

Error trace

```text
Exception has occurred: KeyError
'ti (musical note)'
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 230, in process_word
    vocabulary[the_word] = json.loads(result.content)[the_word]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 232, in generate_vocabulary
    await asyncio.gather(*[process_word(word) for word in words])
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 145, in setup_puzzle
    vocabulary = await generate_vocabulary(state["words_remaining"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/embedvec_tools.py", line 912, in run_workflow
    async for chunk in workflow_graph.astream(None, runtime_config, stream_mode="values"):
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 137, in main
    result = await run_workflow(
             ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/connection_solver/src/agent/app_embedvec.py", line 150, in <module>
    asyncio.run(main(manual_puzzle_setup_prompt, interact_with_user))
KeyError: 'ti (musical note)'
```

LLM Output
```text
result
AIMessage(content='{\n  "ti": [\n    "noun: The seventh note in the diatonic scale of C major, also known as the leading tone.",\n    "noun: In solfège, a system used for teaching pitch and sight-singing, \'ti\' represents the note B in the fixed do system."\n  ]\n}', additional_kwargs={'parsed': None, 'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 66, 'prompt_tokens': 205, 'total_tokens': 271, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_a79d8dac1f', 'finish_reason': 'stop', 'logprobs': None}, id='run-25066280-bf07-4bfd-bf74-ce0c2ec73481-0', usage_metadata={'input_tokens': 205, 'output_tokens': 66, 'total_tokens': 271, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})
print(result.content)
{
  "ti": [
    "noun: The seventh note in the diatonic scale of C major, also known as the leading tone.",
    "noun: In solfège, a system used for teaching pitch and sight-singing, 'ti' represents the note B in the fixed do system."
  ]
}
```

Issue appears to be LLM does not return the original word text as key in json.  It strips the context "hint" aka "(musical note)"  from the key.
