### ISSUE TITLE
Encountered RuntimeError Event Loop is closed during development of Web UI

### ISSUE THREAD

**Issue by jimthompson5802** [jimthompson5802/connection_solver#72]
> Task exception was never retrieved future: <Task finished name='Task-139' coro=<AsyncClient.aclose() done, defined at /usr/local/lib/python3.11/site-packages/httpx/_client.py:1978> exception=RuntimeError('Event loop is closed')> Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1985, in aclose await self._transport.aclose() File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 406, in aclose await self._pool.aclose() File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 353, in aclose await self._close_connections(closing_connections) File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 345, in _close_connections await connection.aclose() File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 173, in aclose await self._connection.aclose() File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 258, in aclose await self._network_stream.aclose() File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 53, in aclose await self._stream.aclose() File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 201, in aclose await self.transport_stream.aclose() File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1349, in aclose self._transport.close() File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 860, in close self._loop.call_soon(self._call_connection_lost, None) File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon self._check_closed() File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed raise RuntimeError('Event loop is closed') RuntimeError: Event loop is closed

**Comment by jimthompson5802** [comment]
anaylsis of error by GHCP:

> The error you're encountering is due to the event loop being closed while there are still pending asynchronous tasks. This can happen when using asynchronous code with Flask, which is not natively designed to handle asynchronous routes.

> To resolve this issue, you can use Quart, an asynchronous web framework compatible with Flask, which allows you to use async and await in your route handlers.

> Here's how you can modify your [entry_app.py] to use Quart
